version: '3.8'

services:
  db:
    image: postgres:15
    container_name: hotel
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: latifa
      POSTGRES_DB: hotel
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


  flyway:
    image: flyway/flyway:latest
    container_name: flyway
    depends_on:
      - db
    environment:
      FLYWAY_URL: jdbc:postgresql://db:5432/hotel
      FLYWAY_USER: postgres
      FLYWAY_PASSWORD: latifa
    volumes:
      - ./sql:/flyway/sql
    entrypoint: [ "flyway", "migrate" ]


volumes:
  postgres_data:
